apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prometheus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-prometheus-app
  template:
    metadata:
      labels:
        app: flask-prometheus-app
    spec:
      containers:
        - name: flask-prometheus-app
          image: your-docker-username/flask-prometheus-app:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-prometheus-service
spec:
  selector:
    app: flask-prometheus-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
